(TeX-add-style-hook "input-grammar"
 (lambda ()
    (LaTeX-add-index-entries
     "SPEX!grammar!paramters"
     "model!comment"
     "convergence!value"
     "iteration limit"
     "print interval"
     "under-relaxation coefficient"
     "scheduling!processor"
     "replication!processor"
     "processor!scheduling!completely fair"
     "processor!sharing"
     "processor!scheduling!sharing"
     "quantum"
     "scheduling!task"
     "queue length"
     "think time"
     "replication!task"
     "group share"
     "fan-in"
     "fan-out"
     "scheduling!semaphore"
     "forwarding probability"
     "histogram"
     "maximum service time"
     "service time!maximum"
     "semaphore!signal"
     "coefficient of variation"
     "phase!type"
     "priority!entry"
     "service time"
     "rendezvous"
     "send-no-reply"
     "activity!connection|see{precedence}"
     "activity!connection"
     "->@\\texttt{->}|see{precedence}"
     "join-list"
     "AND-join"
     "OR-join"
     "and-fork"
     "or-fork"
     "LOOP"
     "quorum"
     "SPEX!grammar!report"
     "SPEX!grammar!convergence"
     "SPEX!grammar!expressions"
     "identifiers"
     "SPEX!variables")
    (LaTeX-add-labels
     "sec:spex-parameters"
     "sec:general-in"
     "sec:processor"
     "sec:group"
     "sec:task"
     "sec:entry"
     "sec:activity"
     "sec:spex-expressions")
    (TeX-add-symbols
     '("altflg" 1)
     "swapflg"
     "tmpflg"
     "chgflg"
     "altflg")))

