(TeX-add-style-hook "lqn-input-grammar"
 (lambda ()
    (LaTeX-add-index-entries
     "model!comment"
     "convergence!value"
     "iteration limit"
     "print interval"
     "under-relaxation coefficient"
     "scheduling!processor"
     "replication!processor"
     "processor!scheduling!completely fair"
     "processor!sharing"
     "processor!scheduling!sharing"
     "quantum"
     "scheduling!task"
     "queue length"
     "think time"
     "replication!task"
     "group share"
     "scheduling!semaphore"
     "forwarding probability"
     "histogram"
     "maximum service time"
     "service time!maximum"
     "semaphore!signal"
     "coefficient of variation"
     "phase!type"
     "fan-in"
     "fan-out"
     "priority!entry"
     "service time"
     "rendezvous"
     "send-no-reply"
     "activity!connection|see{precedence}"
     "activity!connection"
     "->@\\texttt{->}|see{precedence}"
     "join-list"
     "AND-join"
     "OR-join"
     "and-fork"
     "or-fork"
     "LOOP"
     "quorum"
     "expression"
     "identifiers")
    (LaTeX-add-labels
     "sec:general-in"
     "sec:processor"
     "sec:group"
     "sec:task"
     "sec:entry"
     "sec:activity")
    (TeX-add-symbols
     '("altflg" 1)
     "swapflg"
     "tmpflg"
     "chgflg"
     "altflg")))

