(TeX-add-style-hook "lqns"
 (lambda ()
    (LaTeX-add-index-entries
     "LQNS"
     "input!XML"
     "output!XML"
     "XML"
     "XML!input"
     "advisory!ignore"
     "throughput!bounds"
     "bounds!throughput"
     "debug"
     "floating point!exception"
     "overflow"
     "infinity"
     "floating point!infinity"
     "output"
     "standard input"
     "pragma"
     "tracing"
     "results!intermediate"
     "version"
     "copyright"
     "warning!ignore"
     "convergence!value"
     "MVA!exact"
     "MVA!Bard-Schweitzer"
     "LQX"
     "LQX!debug"
     "XML!debug"
     "exit!success"
     "convergence!failure"
     "input!invalid"
     "command line!incorrect"
     "error!fatal"
     "environment variable"
     "LQNS\\_PRAGMAS@\\texttt{LQNS\\_PRAGMAS}"
     "pragma!invalid"
     "cycle!detection"
     "call graph"
     "deadlock"
     "interlock"
     "throughput!interlock"
     "layering!strategy"
     "batched layers"
     "layering!batched"
     "hardware-software layers"
     "layers!hardware-software"
     "method of layers"
     "layering!method of"
     "Method of Layers"
     "layering!Method of Layers"
     "squashed layers"
     "layering!squashed"
     "srvn layers"
     "layering!srvn"
     "multiserver!algorithm"
     "multiserver!Bruell"
     "multiserver!Conway"
     "multiserver!Reiser"
     "processor!sharing"
     "multiserver!Rolia"
     "multiserver!Schmidt"
     "multiserver!default"
     "MVA"
     "MVA!Linearizer"
     "Linearizer"
     "Bard-Schweitzer"
     "overtaking"
     "overtaking!Markov"
     "overtaking!Method of Layers"
     "scheduling!processor"
     "processor!scheduling"
     "priority!head of line"
     "prioity!premptive-resume"
     "processor sharing"
     "arrival rate"
     "open arrival!overflow"
     "send-no-reply!overflow"
     "fork"
     "join"
     "three-point approximation"
     "Mak-Lundstrom"
     "join!delay"
     "overlap calculation"
     "variance"
     "variance!initialize only"
     "variance!Method of Layers"
     "Method of Layers!variance"
     "convergence"
     "iteration limit|textbf"
     "convergence!value|textbf"
     "iteration limit"
     " phase!maximum"
     " scheduling"
     " open arrival"
     " phase!type"
     " think time"
     " coefficient of variation"
     " interprocessor delay"
     " asynchronous connections"
     " forwarding"
     " multi-server"
     " infinite server"
     " entry!maxium"
     " task!maximum"
     " processor!maximum"
     "limits!lqns")
    (LaTeX-add-labels
     "sec:invoking-lqns"
     "sec:options"
     "sec:lqns-pragmas"
     "sec:lqns-stopping-criteria"
     "sec:model-limits"
     "tab:lqns-model-limits"
     "sec:lqns-diagnostics")))

