(TeX-add-style-hook "lqsim"
 (lambda ()
    (LaTeX-add-index-entries
     "Parasol"
     "output!parseable"
     "input!XML"
     "XML"
     "output!XML"
     "command line"
     "automatic blocking"
     "block!automatic"
     "block!size"
     "simulation!block"
     "block!simulation"
     "run time!simulation"
     "precision!simulation"
     "confidence level"
     "skip period"
     "statistics"
     "simulation!statistics"
     "confidence intervals"
     "file!monitor"
     "monitor file"
     "manual blocking"
     "block!manual"
     "skip"
     "initial-loops"
     "task!reference"
     "reference task"
     "floating point!exception"
     "overflow"
     "infinity"
     "floating point!infinity"
     "service time!distribution"
     "distribution!service time"
     "output!csv"
     "file!debug"
     "file!tracing"
     "output"
     "standard input"
     "pragma"
     "counters!statistical"
     "statistical counters"
     "cycle-time!task"
     "cycle-time!entry"
     "utilization!task"
     "utilization!processor"
     "utilization!entry"
     "waiting time"
     "seed"
     "random number!generation"
     "tracing"
     "processor!trace"
     "trace!processor"
     "task!trace"
     "trace!task"
     "statistics!simulation"
     "solution!statistics"
     "version"
     "copyright"
     "warning!ignore"
     "delay!interprocessor"
     "LQX"
     "LQX!debug"
     "XML!debug"
     "exit!success"
     "convergence!failure"
     "input!invalid"
     "command line!incorrect"
     "error!fatal"
     "input!multiple"
     "environment variable"
     "LQSIM\\_PRAGMAS@\\texttt{LQSIM\\_PRAGMAS}"
     "environment
  variable!override"
     "pragma!invalid!command line"
     "pragma!invalid!input file"
     "processor!scheduling"
     "processor!scheduling!custom"
     "processor!utilization"
     "waiting!processor"
     "processor!waiting"
     "processor!scheduling!natural"
     "reschedule!phase"
     "phase!reschedule"
     "reschedule!activity"
     "activity!reschedule"
     "message!buffers"
     "arrival rate"
     "open arrival!overflow"
     "send-no-reply!overflow"
     "send-no-reply"
     "stopping criteria"
     "length!simulation"
     "batch means"
     "method of samples"
     "root mean square"
     "service time!entry"
     "service time!demand"
     "phase!maximum"
     "scheduling"
     "open arrival"
     "phase!type"
     "think time"
     "coefficient of variation"
     "interprocessor delay"
     "asynchronous connections"
     "forwarding"
     "multi-server"
     "infinite server"
     "entry!maximum"
     "task!maximum"
     "processor!maximum"
     "limits!lqsim")
    (LaTeX-add-labels
     "sec:invoking-lqsim"
     "sec:lqsim-options"
     "sec:lqsim-return-status"
     "sec:lqsim-pragmas"
     "sec:stopping-criteria"
     "sec:lqsim-model-limits"
     "tab:lqsim-model-limits")))

