(TeX-add-style-hook "schema"
 (lambda ()
    (LaTeX-add-index-entries
     "XML Grammar(|"
     "Grammar!XML(|"
     "components"
     "lqn.xsd"
     "lqn-sub.xsd"
     "lqn-core.xsd"
     "input!XML"
     "lqns!convergence value"
     "iteration limit"
     "print interval!lqns"
     "statistics!blocked"
     "print interval"
     "scheduling!completely fair"
     "processor!sharing"
     "share!cap"
     "share!guarantee"
     "activity graph"
     "open arrival"
     "activity"
     "activity!demand"
     "demand"
     "activity graph!task"
     "reply!activity"
     "call order"
     "request"
     "activity graph!connection"
     "join!delay"
     "forwarding"
     "activity!results"
     "results!activity"
     "results!phase"
     "phase!results"
     "service time"
     "coefficient of variation"
     "activity graph!start"
     "rendezvous"
     "send-no-reply"
     "join-list"
     "fork-list"
     "branch!probability"
     "probability!branch"
     "branch!loop count"
     "loop count"
     "loop"
     "join!and"
     "join!quorum"
     "quorum~join"
     "utilization!processor"
     "queueing time!processor"
     "waiting time!open arrival"
     "loss probability"
     "service time!variance"
     "service time!probability exceeded"
     "throughput!bounds"
     "throughput"
     "utilization!task"
     "utilization!entry"
     "rendezvous!delay"
     "rendezvous!variance"
     "join!variance"
     "histogram"
     "service time!histogram"
     "schema!constraints"
     "Xerces"
     "activity!connection"
     "precedence"
     "attribute!unique phase"
     "Xerces!error messages"
     "constraint checking"
     "XML!validation"
     "XMLSpy"
     "XSDvalid"
     "Xerces!validation"
     "XML Grammar)|"
     "Grammar!XML)|")
    (LaTeX-add-labels
     "sec:xml-grammar"
     "sec:xml-file-structure"
     "fig:xml-file-layout"
     "sec:schema-elements"
     "fig:Schema"
     "sec:LqnModelType"
     "fig:LqnModelType"
     "tab:LqnModelType"
     "tab:solver-params"
     "tab:result-general"
     "tab:pragma"
     "sec:ProcessorType"
     "fig:ProcessorType"
     "tab:ProcessorType"
     "sec:GroupType"
     "tab:GroupType"
     "sec:TaskType"
     "fig:TaskType"
     "tab:TaskType"
     "sec:EntryType"
     "fig:EntryType"
     "tab:EntryType"
     "sec:ActivityGraphBase"
     "fig:ActivityGraphBase"
     "sec:TaskActivityGraph"
     "tab:reply-entry"
     "tab:reply-activity"
     "sec:ActivityDefBase"
     "tab:ActivityDefBase"
     "sec:MakingCallType"
     "fig:MakingCallType"
     "tab:MakingCallType"
     "sec:PrecedenceType"
     "fig:PrecedenceType"
     "tab:AndJoinListType"
     "tab:ActivityOrType"
     "tab:ActivityLoopListType"
     "tab:ActivityLoopType"
     "sec:OutputResultType"
     "fig:OutputResultType"
     "tab:ResultContentType"
     "sec:OutputResultJoinDelayType"
     "fig:OutputResultJoinDelayType"
     "tab:OutputResultJoinDelay"
     "sec:OutputDistributionType"
     "fig:OutputDistributionType"
     "tab:OutputDistributionType"
     "sec:HistogramBinType"
     "tab:HistogramBinType"
     "sec:schema-constraints")))

