(TeX-add-style-hook "srvn"
 (lambda ()
    (LaTeX-add-index-entries
     "SPEX"
     "SPEX!parameters"
     "SPEX!results"
     "SPEX!convergence"
     "\\#"
     "\\#pragma"
     "pragma"
     "LQN|(textbf"
     "LQNS!parameters"
     "SPEX!parameter!control"
     "scheduling!FCFS"
     "scheduling!head-of-line"
     "scheduling!completely fair"
     "think time"
     "scheduling!fair share"
     "task!reference"
     "reference task"
     "entry!service time"
     "coefficient of variation"
     "signal"
     "semaphore task"
     "LQN!entry"
     "LQN!activity"
     "activity!LQN"
     "LQN|)"
     "SPEX|(textbf"
     "lqiolib"
     "lqx"
     "SPEX!variables|(textbf"
     "SPEX!variables!control"
     "SPEX!variables!scalar"
     "?:"
     "SPEX!ternary expressions"
     "SPEX!variables!array"
     "SPEX!variables!observation"
     "SPEX!report"
     "variables!report indication"
     "variables!parameters"
     "Gnuplot"
     "Excel"
     "\\$0"
     "SPEX!versions"
     "Perl!SPEX"
     "SPEX!LQX"
     "SPEX!arrays"
     "[]"
     "SPEX!Perl"
     "Convergence!SPEX"
     "SPEX!if-then-else"
     "line continuation"
     "\\textbackslash"
     "SPEX!AGR"
     "SPEX|)"
     "LQX")
    (LaTeX-add-labels
     "ch:srvn"
     "sec:lqn-identifiers"
     "LQN!identifiers|textbf"
     "sec:lqn-variables"
     "LQN!variables|textbf"
     "sec:lqn-file-format"
     "sec:lqn-general-information"
     "sec:lqn-processor-information"
     "tab:lqn-proc-sched"
     "tab:lqn-multiplicity"
     "sec:lqn-group-information"
     "sec:lqn-task-information"
     "tab:lqn-task-sched"
     "tab:lqn-task-think-time"
     "sec:lqn-entry-information"
     "tab:lqn-entry-specifier"
     "sec:lqn-activity-information"
     "tab:lqn-activity-specifier"
     "tab:lqn-activity-lists"
     "sec:spex"
     "sec:spex-variables"
     "sec:spex-control"
     "tab:spex-control"
     "sec:spex-scalar"
     "sec:spex-array"
     "sec:spex-observation"
     "tab:obs-location"
     "sec:spex-variables|)"
     "sec:lqn-report-information"
     "sec:lqn-convergence-information"
     "fig:spex-array-initialization")
    (TeX-add-symbols
     '("nonterminal" 1))))

